package com.ltu.m7019e.forktales.database

import com.ltu.m7019e.forktales.model.Recipe

class Recipes {
    fun getRecipes(): List<Recipe> {
        return listOf<Recipe>(
            Recipe(
                53060,
                "Burek",
                "Side",
                "Croatian",
                "Fry the finely chopped onions and minced meat in oil. Add the salt and pepper. Grease a round baking tray and put a layer of pastry in it. Cover with a thin layer of filling and cover this with another layer of filo pastry which must be well coated in oil. Put another layer of filling and cover with pastry. When you have five or six layers, cover with filo pastry, bake at 200°F for half an hour and cut in quarters and serve.",
                "https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg",
                "Streetfood, Onthego",
                "https://www.youtube.com/watch?v=YsJXZwE5pdY",
                "Filo Pastry",
                "Minced Beef",
                "Onion",
                "Oil",
                "Salt",
                "Pepper",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "1 Packet",
                "150g",
                "150g",
                "40g",
                "Dash",
                "Dash",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/",
                "",
            ),
            Recipe(
                52982,
                "Spaghetti alla Carbonara",
                "Pasta",
                "Italian",
                "STEP 1\r\nPut a large saucepan of water on to boil.\r\n\r\nSTEP 2\r\nFinely chop the 100g pancetta, having first removed any rind. Finely grate 50g pecorino cheese and 50g parmesan and mix them together.\r\n\r\nSTEP 3\r\nBeat the 3 large eggs in a medium bowl and season with a little freshly grated black pepper. Set everything aside.\r\n\r\nSTEP 4\r\nAdd 1 tsp salt to the boiling water, add 350g spaghetti and when the water comes back to the boil, cook at a constant simmer, covered, for 10 minutes or until al dente (just cooked).\r\n\r\nSTEP 5\r\nSquash 2 peeled plump garlic cloves with the blade of a knife, just to bruise it.\r\n\r\nSTEP 6\r\nWhile the spaghetti is cooking, fry the pancetta with the garlic. Drop 50g unsalted butter into a large frying pan or wok and, as soon as the butter has melted, tip in the pancetta and garlic.\r\n\r\nSTEP 7\r\nLeave to cook on a medium heat for about 5 minutes, stirring often, until the pancetta is golden and crisp. The garlic has now imparted its flavour, so take it out with a slotted spoon and discard.\r\n\r\nSTEP 8\r\nKeep the heat under the pancetta on low. When the pasta is ready, lift it from the water with a pasta fork or tongs and put it in the frying pan with the pancetta. Don\u2019t worry if a little water drops in the pan as well (you want this to happen) and don\u2019t throw the pasta water away yet.\r\n\r\nSTEP 9\r\nMix most of the cheese in with the eggs, keeping a small handful back for sprinkling over later.\r\n\r\nSTEP 10\r\nTake the pan of spaghetti and pancetta off the heat. Now quickly pour in the eggs and cheese. Using the tongs or a long fork, lift up the spaghetti so it mixes easily with the egg mixture, which thickens but doesn\u2019t scramble, and everything is coated.\r\n\r\nSTEP 11\r\nAdd extra pasta cooking water to keep it saucy (several tablespoons should do it). You don\u2019t want it wet, just moist. Season with a little salt, if needed.\r\n\r\nSTEP 12\r\nUse a long-pronged fork to twist the pasta on to the serving plate or bowl. Serve immediately with a little sprinkling of the remaining cheese and a grating of black pepper. If the dish does get a little dry before serving, splash in some more hot pasta water and the glossy sauciness will be revived.",
                "https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg",
                "Pasta,BBQ,Breakfast",
                "https://www.youtube.com/watch?v=_T6jkRvhlkk",
                "Spaghetti",
                "Egg Yolks",
                "Salt",
                "Bacon",
                "Pecorino",
                "Black Pepper",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "320g",
                "6",
                "As required",
                "150g",
                "50g",
                "As required",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "https://www.bbcgoodfood.com/recipes/ultimate-spaghetti-carbonara-recipe",
                "",
            ),
            Recipe(
                52927,
                "Montreal Smoked Meat",
                "Beef",
                "Canadian",
                "To make the cure, in a small bowl mix together salt, pink salt, black pepper, coriander, sugar, bay leaf, and cloves. Coat entire brisket with the cure and place in an extra-large resealable plastic bag. Place in the coldest part of the refrigerator and cure for 4 days, flipping brisket twice a day.\r\nRemove brisket from bag and wash as much cure off as possible under cold running water. Place brisket in a large container and fill with water and let soak for 2 hours, replacing water every 30 minutes. Remove from water and pat dry with paper towels.\r\nTo make the rub, mix together black pepper, coriander, paprika, garlic powder, onion powder, dill weed, mustard, celery seed, and crushed red papper in a small bowl. Coat entire brisket with the rub.\r\nFire up smoker or grill to 225 degrees, adding chunks of smoking wood chunks when at temperature. When wood is ignited and producing smoke, place brisket in, fat side up, and smoke until an instant read thermometer registers 165 degrees when inserted into thickest part of the brisket, about 6 hours.\r\nTransfer brisket to large roasting pan with V-rack. Place roasting pan over two burners on stovetop and fill with 1-inch of water. Bring water to a boil over high heat, reduce heat to medium, cover roasting pan with aluminum foil, and steam brisket until an instant read thermometer registers 180 degrees when inserted into thickest part of the meat, 1 to 2 hours, adding more hot water as needed.\r\nTransfer brisket to cutting board and let cool slightly. Slice and serve, preferably on rye with mustard.",
                "https://www.themealdb.com/images/media/meals/uttupv1511815050.jpg",
                "Speciality,Snack,StrongFlavor",
                "https://www.youtube.com/watch?v=g5oCDoyxbBk",
                "Beef Brisket",
                "Salt",
                "Black Pepper",
                "Coriander",
                "Sugar",
                "Bay Leaf",
                "Cloves",
                "Black Pepper",
                "Coriander",
                "Paprika",
                "Garlic",
                "Onion",
                "Dill",
                "English Mustard",
                "Celery Salt",
                "Red Pepper Flakes",
                "",
                "",
                "",
                "",
                "1",
                "3 tbs",
                "3 tbs",
                "1 tbs",
                "1 tbs",
                "1 tsp",
                "1 tsp",
                "3 tbs",
                "1 tbs",
                "1 tbs",
                "1 tbs",
                "1 tbs",
                "1 tbs",
                "1 tsp",
                "1 tbs",
                "1 tsp",
                "",
                "",
                "",
                "",
                "http://www.meatwave.com/blog/montreal-smoked-meat-recipe",
                "",
            )
        )
    }
}